# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    controller:
        redirect_response_code: 302
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        game_home:
            quality: 100
            filters:
                thumbnail: { size: [ 445, 445 ], mode: outbound }
        game_index:
            quality: 100
            filters:
                thumbnail: { size: [ 250, 230 ], mode: outbound }
        avatar:
            quality: 100
            filters:
                thumbnail: { size: [ 96, 96 ], mode: outbound }