twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/front': front
        '%kernel.project_dir%/templates/ui': ui
        '%kernel.project_dir%/templates/email': email
        '%kernel.project_dir%/public': public
        '%kernel.project_dir%/templates/bundles': bundles
