vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        storages:
            uri_prefix: /uploads/storages
            upload_destination: '%kernel.project_dir%/templates/uploads/storages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'user.slug', transliterate: true }
