#!/bin/sh
rsync -av ./ esvf5457@roliste-chaotique.be:~/roliste-chaotique.be --include=.env --include=public/build --include=public/.htaccess --exclude=vendor --exclude-from=.gitignore --exclude=".*"  --exclude=tests --exclude=src/DataFixtures --exclude=config/secrets/dev --exclude=config/package/dev --exclude=config/package/test --exclude=assets
