#!/bin/sh
rsync -av ./ esvf5457@roliste-chaotique.be:~/roliste-chaotique.be \
--exclude-from=.gitignore \
--exclude=deploy \
--exclude=".*" \
--include=.env \
--exclude=vendor \
--exclude=tests \
--exclude=src/DataFixtures \
--exclude=config/secrets/dev \
--exclude=config/package/dev \
--exclude=config/package/test \
--exclude=assets \
--include=public/build \
--include=public/.htaccess